# Change these first
owner: givefood # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Give Food Homepage
    url: https://www.givefood.org.uk/
  - name: Give Food API 1
    url: https://www.givefood.org.uk/api/1/foodbanks/
  - name: Give Food API 2
    url: https://www.givefood.org.uk/api/2/foodbanks/
  - name: Give Food API 2 Needs
    url: https://www.givefood.org.uk/api/2/needs/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.givefood.org.uk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
