# Change these first
owner: givefood # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Give Food Homepage
    url: https://www.givefood.org.uk/
  - name: Give Food API 1 food banks dump
    url: https://www.givefood.org.uk/api/1/foodbanks/
  - name: Give Food API 2 food banks dump
    url: https://www.givefood.org.uk/api/2/foodbanks/
  - name: Give Food API 2 individual food bank
    url: https://www.givefood.org.uk/api/2/foodbank/sid-valley/
  - name: Give Food API 2 locations dump
    url: https://www.givefood.org.uk/api/2/locations/
  - name: Give Food API 2 location search
    url: https://www.givefood.org.uk/api/2/locations/search/?lat_lng=51.178889,-1.826111
  - name: Give Food API 2 Needs
    url: https://www.givefood.org.uk/api/2/needs/
  - name: Datasette
    url: https://datasette.givefood.org.uk/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.givefood.org.uk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.givefood.org.uk/static/img/logo.png
  name: Give Food
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
